version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dashboard
hooks:
  BeforeInstall:
    - location: scripts/setup_directory.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 90
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user